inline_attribute_width = 50
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
#report_todo = "Always"
single_line_if_else_max_width = 100
trailing_semicolon = false
use_field_init_shorthand = true
combine_control_expr = false
condense_wildcard_suffixes = true
force_multiline_blocks = true
max_width = 150
use_try_shorthand = true