blank_issues_enabled: true
contact_links:
  - name: Fire Emblem Hacks & Mods
    url: https://discord.gg/5ANBhPS
    about: If you having trouble with Cobalt, want to learn or ask questions, ask here
